name: Trigger auto deployment for testingcats

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'docker-compose.yml/**'
    - '.github/workflows/testingcats-AutoDeployTrigger-41e611db-63e9-4335-a249-04a1c1a0e5fe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTINGCATS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTINGCATS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTINGCATS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/docker-compose.yml 
          registryUrl: webapplication220240506135353.azurecr.io
          registryUsername: ${{ secrets.TESTINGCATS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTINGCATS_REGISTRY_PASSWORD }}
          containerAppName: testingcats
          resourceGroup: DefaultResourceGroup-WEU
          imageToBuild: webapplication220240506135353.azurecr.io/testingcats:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


